plex_url: http://192.168.50.203:32400
plex_api_key: eTyU6reY7qi-P4wcz51D
movie_library_name: "Movies"
tv_library_name: "TV Shows"
remove_from_watchlist: true
check_movies: true
check_tv_shows: true

# Scheduler options
enable_scheduler: false
run_interval: 24
purge_all_watchlist: true

users: Admin
